name: bitacoras
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_svg: ^2.0.17
  get_it: ^8.0.3
  go_router: ^14.7.2
  google_fonts: ^6.2.1
  hydrated_bloc: ^10.0.0
  intl: ^0.20.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/illustration/
    - assets/lotties/
